- type: job
  id: BoSMidPaladinCommander
  setPreference: true
  name: Midwest paladin commander
  description: Lead the midwest exploration team, follow the objetives and take decisions to take control over the wasteland.
  playTimeTracker: BoSMidPaladinCommander
  startingGear: BoSMidPaladinCommGear
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  
- type: startingGear
  id: BoSMidPaladinCommGear
  equipment:
    jumpsuit: N14ClothingUniformBosRecon
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    hands: N14ClothingHandsGlovesCombat
    id: N14IDBrotherhoodHolotag
    ears: N14ClothingHeadsetBOSMidwest
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidPaladinCommander
