- type: job
  id: BoSMidScribe
  setPreference: false # Delete line for RP
  name: job-name-bos-mid-scribe
  description: job-description-bos-mid-scribe
  playTimeTracker: BoSMidScribe
  startingGear: BoSMidScribeGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-mid
  access:
  - ScribeMidwest

- type: startingGear
  id: BoSMidScribeGear
  equipment:
    head: ClothingHeadBrotherhoodScribeHeadset
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackSatchelMilitary
    shoes: N14ClothingBootsCombat
    outerClothing: N14ClothingOuterMidwestBoSCoat
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetScience #placeholder
    belt: N14ClothingBeltUtilityFilled
  
- type: playTimeTracker
  id: BoSMidScribe
