- type: job
  id: BoSMidSquire
  setPreference: true
  name: Midwest squire
  description: Follow orders and become the hardened steel the brotherhood wants you to be.
  playTimeTracker: BoSMidSquire
  startingGear: BoSMidSquire
  icon: "JobIconPassenger"
  canBeAntag: false
  accessGroups:
  - BOSMidwest
  
- type: startingGear
  id: BoSMidSquire
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSGreen
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    head: N14ClothingHeadHatBrotherhoodMidwestHelmet
    outerClothing: N14ClothingOuterMidwestArmor
    id: N14IDBrotherhoodHolotag
    belt: ClothingBeltMilitary

- type: playTimeTracker
  id: BoSMidSquire
