- type: job
  id: BoSWashingtonCommander
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-commander
  description: job-description-bos-washington-commander
  playTimeTracker: BoSWashingtonCommander
  weight: 10
  startingGear: BoSWashingtonCommanderGear
  icon: "JobIconHeadOfSecurity"
  supervisors: job-supervisors-bos-washington-commander
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - BOSWashington

- type: startingGear
  id: BoSWashingtonCommanderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSBlack
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatMK2
    neck: ClothingNeckCloakBrotherhoodWashington
    head: N14ClothingHeadHatBrotherhoodBeret
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetAltSecurity #placeholder
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSWashingtonCommander
