- type: job
  id: BoSWashingtonRecruit
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-Recruit
  description: job-description-bos-washington-Recruit
  playTimeTracker: BoSWashingtonRecruit
  startingGear: BoSWashingtonRecruitGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington-recruit
  canBeAntag: false
  access:
  - WashingtonInitiate

- type: startingGear
  id: BoSWashingtonRecruitGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombat
    id: N14IDBrotherhoodHolotag
    outerClothing: N14ClothingOuterCombatArmorBOS
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSWashingtonRecruit
