- type: job
  id: BoSWashingtonSoldier
  setPreference: false # Delete line for RP
  name: job-name-bos-washington-soldier
  description: job-description-bos-washington-soldier
  playTimeTracker: BoSWashingtonSoldier
  startingGear: BoSWashingtonSoldierGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-bos-washington
  canBeAntag: false
  access:
  - WashingtonInitiate
  - WashingtonKnight
  
- type: startingGear
  id: BoSWashingtonSoldierGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitBOSRed
    back: N14ClothingBackpackMilitary
    shoes: N14ClothingBootsCombatMK2
    hands: N14ClothingHandsGlovesCombat
    head: N14ClothingHeadHatBrotherhoodHelmet
    outerClothing: N14ClothingOuterCombatArmorBOSMK2
    id: N14IDBrotherhoodHolotag
    ears: ClothingHeadsetSecurity #placeholder
    belt: ClothingBeltBoSWebbing

- type: playTimeTracker
  id: BoSWashingtonSoldier
