- type: job
  id: CaravanTrader
  setPreference: false # Delete line for RP
  name: job-name-caravan-trader
  description: job-description-caravan-trader
  playTimeTracker: CaravanTrader
  startingGear: CaravanTraderGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-caravan
  access:
  - CaravanCompanyTrader
  - CaravanCompanyGuard

- type: startingGear
  id: CaravanTraderGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitTrader
    back: N14ClothingBackpackCaravanTraderFilled
    shoes: N14ClothingBootsLeather
    id: N14IDPassportCaravan
  innerClothingSkirt: N14ClothingUniformJumpsuitTrader #placeholder

- type: playTimeTracker
  id: CaravanTrader
