- type: job
  id: TownSheriff
  setPreference: false # Delete line for RP
  name: job-name-townsheriff
  description: job-description-townsheriff
  playTimeTracker: TownSheriff
  startingGear: TownSheriffGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk

- type: startingGear
  id: TownSheriffGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCowboyGrey
    back: N14ClothingBackpackSheriffFilled
    shoes: N14ClothingBootsCowboy
    head: N14ClothingHeadHatSheriff
    id: N14IDBadgeTownSheriff
    outerClothing: N14ClothingOuterSheriffVest
    pocket1: RadioHandheld
    pocket2: N14WeaponHunterRevolver
    belt: N14ClothingBeltPoliceFilled
    suitstorage: N14WeaponLeverRifle

- type: playTimeTracker
  id: TownSheriff
