- type: job
  id: TownMayor
  setPreference: false # Delete line for RP
  name: job-name-townmayor
  description: job-description-townmayor
  playTimeTracker: TownMayor
  startingGear: TownMayorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-townsfolk

- type: startingGear
  id: TownMayorGear
  equipment:
    jumpsuit: N14ClothingUniformJumpsuitCheckered
    back: N14ClothingBackpackMayorFilled
    shoes: N14ClothingShoesBrown
    belt: N14WeaponPistolChinese
    id: N14IDBadgeTownMayor
    pocket1: RadioHandheld
  innerClothingSkirt: N14ClothingUniformJumpskirtFalloutBlack

- type: playTimeTracker
  id: TownMayor
