- type: job
  id: NCRVeteranRanger
  setPreference: true
  name: desert ranger
  description: Veterans from the NCR rangers and the old desert rangers, they are a elite spec ops group ready to operate at the wasteland, they may or not cooperate with the NCR army.
  playTimeTracker: NCRVeteranRanger
  weight: 10
  startingGear: NCRVeteranRangerGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  canBeAntag: false
  accessGroups:
  - NCR

- type: startingGear
  id: NCRVeteranRangerGear
  equipment:
    jumpsuit: N14ClothingUniformRangerV1
    shoes: N14ClothingBootsCombat
    id: N14IDBadgeNCRDesertRanger
    back: N14ClothingBackpackMilitaryFilled
    ears: ClothingHeadsetAltSecurity #placeholder
  innerClothingSkirt: N14ClothingUniformRangerV1 #placeholder

- type: playTimeTracker
  id: NCRVeteranRanger
