- type: loadout
  id: LoadoutNCRRangerArmor
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerVest
    
- type: loadout
  id: LoadoutNCRRangerArmorV2
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingOuterRangerArmor
    
- type: loadout
  id: LoadoutNCRRangerGun1
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14Weapon50NcrRifle
    - MagazineBox50
    
- type: loadout
  id: LoadoutNCRRangerGun2
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14WeaponCarbine
    - LongMagazine5.56Rifle
    - LongMagazine5.56Rifle
    
- type: loadout
  id: LoadoutNCRRangerGun3
  category: Roles
  cost: 4
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14WeaponLeverRifle
    - MagazineBox308
    
- type: loadout
  id: LoadoutNCR5.56
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - LongMagazine5.56Rifle
    - LongMagazine5.56Rifle
    
- type: loadout
  id: LoadoutNCR50
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - MagazineBox50
    
- type: loadout
  id: LoadoutNCR308
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - MagazineBox308
    
- type: loadout
  id: LoadoutNCRmask1
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasRiot

- type: loadout
  id: LoadoutNCRmask2
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - ClothingMaskGasCombat

- type: loadout
  id: LoadoutNCRhelmet
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRangerHelmet

- type: loadout
  id: LoadoutNCRhat
  category: Roles
  cost: 2
  exclusive: true
  requirements:
    - !type:LoadoutJobRequirement
      jobs:
        - NCRRanger
  items:
    - N14ClothingHeadHatRanger
